# Generated by Django 4.1.1 on 2022-09-06 15:21

import applicants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "years_of_experince",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "department_id",
                    models.CharField(
                        choices=[("IT", "IT"), ("HR", "HR"), ("FIN", "Finance")],
                        default="IT",
                        max_length=3,
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes",
                        validators=[
                            applicants.models.Applicant.validate_file_extension
                        ],
                    ),
                ),
            ],
        ),
    ]
