# Generated by Django 4.1.1 on 2022-09-06 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="regestration_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
